name: Deploy Angular App to AWS S3

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.1' # Set this to the node version you are using

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install npm dependencies
      run: npm install

    - name: Build production app
      run: ng build --prod

    - name: Deploy to AWS S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' # Change this to your bucket's region
        SOURCE_DIR: 'dist/jobber-ui' # Update the path according to your project's output directory